#!/usr/bin/env bash

image_file_path="./src/components/Images.js"
image_path="../images/"
images=()

getImports () {
	# 'import imagePaths from "./Images.js";'
	for i in "${!images[@]}"; do
		echo "import image$i from \"$image_path/${images[$i]}\";"
	done
}

getExportArray () {
	local beginning="export default ["
	local ending="];"
	local exportString=$beginning

	for i in "${!images[@]}"; do
		exportString+="image$i,"
	done

	echo "$exportString$ending"
}

printImagesFile () {
	echo "/***** GENERATED IMAGE IMPORT FILE - created by createImageImports *****/"
	getImports
	getExportArray
}

# images=$(ls ./src/images/*.jpg)

for path in ./src/images/*.jpg; do
	# img="${path##*/}"
    # images+=( "${img%%.*}" )
	images+=( "${path##*/}" )
done

printImagesFile > $image_file_path
